MinistoreFE/Pages/CheckOut.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net.Http.Headers;

namespace MinistoreFE.Pages
{
    public class CheckOutModel : PageModel
    {
        private HttpClient client;
        private string CheckInApi = "https://localhost:7036/CheckOut";
        private string StaffId;
        private string Token;

        public CheckOutModel()
        {
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
        }
        public async Task<IActionResult> OnGetAsync()
        {
            StaffId = HttpContext.Session.GetString("Id");
            Token = HttpContext.Session.GetString("Token");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", Token);
            await client.GetAsync($"{CheckInApi}?id={StaffId}");
            return RedirectToPage("Index");
        }
    }
}

MinistoreFE/Pages/Manager/Duty.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Constants;
using MinistoreFE.Models;
using MinistoreFE.Request;
using Newtonsoft.Json;
using Simple.OData.Client;
using System.Globalization;
using System.Net.Http.Headers;

namespace MinistoreFE.Pages.Manager
{
	public class DutyModel : PageModel
	{
		private ODataClient _odataClient;
		private HttpClient client;
		private string WorkShiftApi = "https://localhost:7036/odata/WorkShifts";
		private string DutyApi = "https://localhost:7036/odata/Duties";
		private string ManagerId;
		public DutyModel()
		{
			_odataClient = OdataUtils.GetODataClient();
			client = new HttpClient();
			var contentType = new MediaTypeWithQualityHeaderValue("application/json");
			client.DefaultRequestHeaders.Accept.Add(contentType);
			Date = DateTime.Now;
		}

		public List<DateOnly> Dates { get; set; }
		public List<WorkShift> WorkShifts { get; set; }
		public List<Models.Staff> AllStaffs { get; set; }
		public List<Models.Staff> FreeStaffs { get; set; } = new List<Models.Staff>();
		public WorkShift CurrentShift { get; set; }
		public DateTime Date { get; set; }
		public async Task<IActionResult> OnGetAsync()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			ManagerId = HttpContext.Session.GetString("Id");
			var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
			WorkShifts = temp.ToList();
			var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
			AllStaffs = staffTmp.Where(s => s.Status == (byte)Status.Available && !Role.IsManager(s.RoleId)).ToList();
			if (WorkShifts.Count == 0)
			{
				WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
				var myContent = JsonConvert.SerializeObject(request);
				var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
				byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
				await client.PostAsync(WorkShiftApi, byteContent);
				temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
				WorkShifts = temp.ToList();
			}
			return Page();
		}
		public async Task<IActionResult> OnPost(string date)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			ManagerId = HttpContext.Session.GetString("Id");

			Date = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
			var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
			WorkShifts = temp.ToList();
			var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
			AllStaffs = staffTmp.Where(s => s.Status == (byte)Status.Available && !Role.IsManager(s.RoleId)).ToList();
			if (WorkShifts.Count == 0)
			{
				WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
				var myContent = JsonConvert.SerializeObject(request);
				var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
				byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
				client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
				await client.PostAsync(WorkShiftApi, byteContent);
				temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
				WorkShifts = temp.ToList();
			}
			return Page();
		}
		public async Task<IActionResult> OnPostUpdate(DateTime date, int dutyId, byte status)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			ManagerId = HttpContext.Session.GetString("Id");

			Models.Duty duty = new Models.Duty { DutyId = dutyId, Status = status };
			var myContent = JsonConvert.SerializeObject(duty);
			var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
			byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
			await client.PostAsync($"{DutyApi}/Update", byteContent);
			return await OnPost(date.ToString("dd/MM/yyyy"));
		}
		public async Task<IActionResult> OnPostDelete(DateTime date, int dutyId)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			ManagerId = HttpContext.Session.GetString("Id");
			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
			await client.DeleteAsync($"{DutyApi}/{dutyId}");
			return await OnPost(date.ToString("dd/MM/yyyy"));
		}
		public async Task<IActionResult> OnPostCreate(DateTime date, int shiftId, string[] staffId)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			ManagerId = HttpContext.Session.GetString("Id");

			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));

			Models.Duty duty;
			foreach (string id in staffId)
			{
				duty = new Models.Duty { ShiftId = shiftId, AssignedTo = id };
				var myContent = JsonConvert.SerializeObject(duty);
				var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
				byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
				await client.PostAsync(DutyApi, byteContent);
			}
			return await OnPost(date.ToString("dd/MM/yyyy"));
		}
	}
}

MinistoreFE/Pages/Manager/Duty/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Models;
using MinistoreFE.Request;
using Newtonsoft.Json;
using Simple.OData.Client;
using System.Globalization;
using System.Net.Http.Headers;

namespace MinistoreFE.Pages.Manager.Duty
{
    public class IndexModel : PageModel
    {
        private ODataClient _odataClient;
        private HttpClient client;
        private string WorkShiftApi = "https://localhost:7036/odata/WorkShifts";
        private string ManagerId = "VyLT1";
        public IndexModel()
        {
            _odataClient = OdataUtils.GetODataClient();
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            Date = DateTime.Now;
        }

        public List<DateOnly> Dates { get; set; }
        public List<WorkShift> WorkShifts { get; set; }
        public List<string> StaffIds { get; set; }
        public List<string> FreeStaffIds { get; set; }
        public DateTime Date { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
            WorkShifts = temp.ToList();
            var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
            StaffIds = staffTmp.Select(s => s.StaffId).ToList();
            if (WorkShifts.Count == 0)
            {
                WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
                var myContent = JsonConvert.SerializeObject(request);
                var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                await client.PostAsync(WorkShiftApi, byteContent);
                temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
                WorkShifts = temp.ToList();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(string date)
        {
            Date = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
            WorkShifts = temp.ToList();
            var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
            StaffIds = staffTmp.Select(s => s.StaffId).ToList();
            if (WorkShifts.Count == 0)
            {
                WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
                var myContent = JsonConvert.SerializeObject(request);
                var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                await client.PostAsync(WorkShiftApi, byteContent);
                temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
                WorkShifts = temp.ToList();
            }
            return Page();
        }
    }
}

MinistoreFE/Pages/Salesman/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Salesman
{
    public class CheckoutModel : PageModel
    {
        private ODataClient _odataClient;
        public CheckoutModel()
        {
            _odataClient = OdataUtils.GetODataClient();
        }

        public IList<Product> Product { get;set; } = default!;

        public async Task<IActionResult> OnGetAsync()
        {
            if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token"))) {
                return RedirectToPage("/Login");
            }
            if (!Utils.isSalesman(HttpContext.Session.GetString("Role"))) {
                return RedirectToPage("/Login");
            }
            _odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
            Product = new List<Product>();
            var cart = HttpContext.Session.GetCustomObjectFromSession<Cart>("Cart");
            if (cart == null) {
                cart = Utils.CreateCart(HttpContext.Session.GetString("Id"));
            }
            foreach (var item in cart.CartItems) {
                var temp = await _odataClient.For<Product>().Key(item.ProductId).Expand(p => p.Category).FindEntryAsync();
                temp.UnitsInStock = item.Quantity;
                Product.Add(temp);
            }
            return Page();
        }

        public async Task<IActionResult> OnPostSubmit() {
            if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token"))) {
                return RedirectToPage("/Login");
            }
            if (!Utils.isSalesman(HttpContext.Session.GetString("Role"))) {
                return RedirectToPage("/Login");
            }

            var cart = HttpContext.Session.GetCustomObjectFromSession<Cart>("Cart");
            if (cart == null) {
                cart = Utils.CreateCart(HttpContext.Session.GetString("Id"));
                return RedirectToPage("/Salesman/Products/Index");
            }

            _odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));

            Invoice invoice = new Invoice { StaffId = cart.StaffId, OrderDate = DateTime.Now, Status = 1, Total = 0, InvoiceDetails = new List<InvoiceDetail>() };
            foreach (var item in cart.CartItems) {
                var product = await _odataClient.For<Product>().Key(item.ProductId).Expand(p => p.Category).FindEntryAsync();
                if (product != null) {
                    var detail = new InvoiceDetail {
                        ProductId = product.ProductId,
                        Discount = item.Discount,
                        UnitPrice = product.UnitPrice,
                        Quantity = item.Quantity
                    };
                    invoice.InvoiceDetails.Add(detail);
                    invoice.Total += detail.Quantity * detail.UnitPrice * (decimal) (1 - detail.Discount);
                }
            }
            await _odataClient.For<Invoice>().Set(invoice).InsertEntryAsync();
            cart.CartItems.Clear();
            HttpContext.Session.SetObjectInSession("Cart", cart);
            return RedirectToPage("/Salesman/Products/Index");
        }

        public async Task<IActionResult> OnPostRemove(int productId) {
            if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token"))) {
                return RedirectToPage("/Login");
            }
            if (!Utils.isSalesman(HttpContext.Session.GetString("Role"))) {
                return RedirectToPage("/Login");
            }

            var cart = HttpContext.Session.GetCustomObjectFromSession<Cart>("Cart");
            if (cart == null) {
                cart = Utils.CreateCart(HttpContext.Session.GetString("Id"));
                return RedirectToPage("/Salesman/Products/Index");
            }

            var item = cart.CartItems.FirstOrDefault(p => p.ProductId == productId);
            if (item != null) {
                cart.CartItems.Remove(item);
            }
            HttpContext.Session.SetObjectInSession("Cart", cart);
            return RedirectToPage();
        }
    }
}

MinistoreFE/Pages/Salesman/Products/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Salesman.Products
{
    public class DetailsModel : PageModel
    {
        private ODataClient _odataclient;

        public DetailsModel()
        {
            _odataclient = OdataUtils.GetODataClient();
        }

      public Product Product { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token"))) {
                return RedirectToPage("/Login");
            }
            if (!Utils.isSalesman(HttpContext.Session.GetString("Role"))) {
                return RedirectToPage("/Login");
            }
            _odataclient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
            Product = await _odataclient.For<Product>().Key(id).Expand(p => p.Category).FindEntryAsync();
            return Page();
        }
    }
}

MinistoreFE/Pages/Salesman/Checkout.cshtml
@page
@model MinistoreFE.Pages.Salesman.CheckoutModel

@{
    ViewData["Title"] = "Checkout";
    Layout = "_LayoutSalesman";
}
<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Salesman</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item">
                    <a asp-page="/Salesman/Dashboard">Salesman</a>
                </li>
                <li class="breadcrumb-item active">Checkout</li>
            </ul>
        </div>
        <div class="col-auto float-end ms-auto">
            <form method="post" asp-page-handler="Submit">
                <input type="submit" class="btn add-btn"/>
            </form>
            
        </div>
    </div>
</div>

<div class="row filter-row">
    <div class="col-sm-6 col-md-9">
        <div class="form-group form-focus">
            <input type="text" class="form-control floating">
            <label class="focus-label">Product Name</label>
        </div>
    </div>
    <div class="col-sm-6 col-md-3">
        <div class="d-grid">
            <a href="#" class="btn btn-success w-100"> Search </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="table-responsive">
            <table class="table table-striped custom-table datatable">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Product[0].ProductName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Product[0].Description)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Product[0].UnitPrice)
                        </th>
                        <th>
                            Quantity
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Product[0].Category)
                        </th>
                        <th>
                            Action
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Product) {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ProductName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UnitPrice)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UnitsInStock)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Category.CategoryName)
                            </td>
                            <td>
                                <form asp-page-handler="Remove" method="post">
                                    <input type="hidden" name="productId" asp-for="@item.ProductId" />
                                    <input type="submit" class="btn btn-danger" value="Remove">
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

MinistoreFE/Pages/Salesman/Duty.cshtml
@page
@model MinistoreFE.Pages.Salesman.DutyModel
@using MinistoreFE.Constants;
@{
	ViewData["Title"] = "Duty";
	Layout = "_LayoutSalesman";
}
<div class="page-header">
	<div class="row align-items-center">
		<div class="col">
			<h3 class="page-title">Salesman</h3>
			<ul class="breadcrumb">
				<li class="breadcrumb-item">
					<a asp-page="/Salesman/Dashboard">Salesman</a>
				</li>
				<li class="breadcrumb-item active">Duty</li>
			</ul>
		</div>
	</div>
</div>

<form class="row filter-row" method="post">
	<div class="col-sm-6 col-md-3 col-lg-3 col-xl-2 col-12">
		<div class="form-group form-focus">
			<div class="cal-icon">
				<input class="form-control floating datetimepicker" name="date" value="@Model.Date.ToString("dd/MM/yyyy")" type="text">
			</div>
			<label class="focus-label">Date</label>
		</div>
	</div>
	<div class="col-sm-6 col-md-3 col-lg-3 col-xl-2 col-12">
		<input type="submit" href="#" class="btn btn-success w-100" value="Search" />
	</div>
</form>

<div>
	<div class="table-responsive">
		<table class="table custom-table">
			<thead>
				<tr>
						@for (var i = 0; i < 7; i++)
						{
						<th>
								@Model.Dates.ElementAt(i).DayOfWeek (@Model.Dates.ElementAt(i).ToString("dd/MM"))
						</th>
						}
				</tr>
			</thead>
			<tbody>
			<tr>

					@for (var i = 0; i < 7; i++)
					{
					<td class="p-0 bg-soft-dark">
							@foreach (var item in Model.Duties)
							{
								if (DateOnly.FromDateTime(item.Shift.StartTime) == Model.Dates.ElementAt(i))
								{
								<div class="card profile-box flex-fill">
									<div class="card-body">
										<ul class="personal-info">
											<li>
												<div class="title">From</div>
												<div class="text">@item.Shift.StartTime.ToString("HH:mm")</div>
											</li>
											<li>
												<div class="title">To</div>
													<div class="text">@item.Shift.EndTime.ToString("HH:mm")</div>
											</li>
											<li>
												<div class="title">Status</div>
												<div class="text">
													<span class="badge bg-inverse-@DutyStatus.GetClassString(item.Status)">@DutyStatus.GetStatus(item.Status)</span>
												</div>
											</li>
										</ul>
									</div>
								</div>
								}

							}
					</td>
					}
			</tr>

			</tbody>
		</table>
	</div>
</div>
<style>
	.card {
		margin-bottom: 0;
		border-radius: 0;
	}

	th {
		width: 200px;
	}

	td {
		width: 400px;
	}

	.table {
		width: fit-content;
	}
	.table td {
		vertical-align: top;
	}
</style>