MinistoreFE/Pages/Manager/Products/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class CreateModel : PageModel
	{
		private ODataClient _odataClient;

		public CreateModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		[BindProperty]
		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			var temp = await _odataClient.For<Category>().FindEntriesAsync();
			ViewData["Category"] = new SelectList(temp.ToList(), "CategoryId", "CategoryName");
			return Page();
		}

		public async Task<IActionResult> OnPostCreate()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));

			Product.Status = 1;
			Product.ProductStatus = 1;
			var temp = await _odataClient.For<Product>().Set(Product).InsertEntryAsync();
			return RedirectToPage("./Index");
		}
	}
}

MinistoreFE/Pages/Manager/Products/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class DeleteModel : PageModel
	{
		private ODataClient _odataClient;

		public DeleteModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product = await _odataClient.For<Product>().Key(id).Expand(p => p.Category).FindEntryAsync();
			return Page();
		}

		public async Task<IActionResult> OnPostDelete(int? productId)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			await _odataClient.For<Product>().Key(productId).DeleteEntryAsync();
			return RedirectToPage("./Index");
		}
	}
}

MinistoreFE/Pages/Manager/Products/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class DetailsModel : PageModel
	{
		private ODataClient _odataClient;

		public DetailsModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product = await _odataClient.For<Product>().Key(id).Expand(p => p.Category).FindEntryAsync();
			return Page();
		}
	}
}

MinistoreFE/Pages/Manager/Products/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class EditModel : PageModel
	{
		private ODataClient _odataClient;

		public EditModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		[BindProperty]
		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product = await _odataClient.For<Product>().Key(id).Expand(p => p.Category).FindEntryAsync();
			var temp = await _odataClient.For<Category>().FindEntriesAsync();
			ViewData["Category"] = new SelectList(temp.ToList(), "CategoryId", "CategoryName");
			return Page();
		}

		public async Task<IActionResult> OnPostEdit()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product.Status = 1;
			Product.ProductStatus = 1;
			await _odataClient.For<Product>().Key(Product.ProductId).Set(Product).UpdateEntryAsync();
			return RedirectToPage("./Details", new { id = Product.ProductId.ToString() });
		}
	}
}

MinistoreFE/Pages/Manager/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class IndexModel : PageModel
	{
		private ODataClient _odataClient;
		public IndexModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		public IList<Product> Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			var temp = await _odataClient.For<Product>().Expand(p => p.Category).FindEntriesAsync();
			Product = temp.ToList();
			return Page();
		}
	}
}

MinistoreFE/Pages/Manager/Staff/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using Simple.OData.Client;
using System.Net.Http.Headers;

namespace MinistoreFE.Pages.Manager.Staff
{
    public class DetailsModel : PageModel
    {
        private ODataClient _odataClient;
        private HttpClient client;

        private string api = "https://localhost:7036/odata/Staffs";
        public DetailsModel()
        {
            _odataClient = OdataUtils.GetODataClient();
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
        }
        public Models.Staff staff { get; set; }
        public decimal salary { get; set; }
        public string role { get; set; }
        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
            {
                return RedirectToPage("/Login");
            }
            if (!Utils.isManager(HttpContext.Session.GetString("Role")))
            {
                return RedirectToPage("/Login");
            }
            var token = HttpContext.Session.GetString("Token");
            _odataClient = OdataUtils.GetODataClient(token);
            var staffs = await _odataClient.For<Models.Staff>().FindEntriesAsync();
            staff = staffs.FirstOrDefault(s => s.StaffId.ToLower().Equals(id.ToLower()));
            if (staff == null)
            {
                return NotFound();
            }
            if (!Constants.Role.IsManager(staff.RoleId))
            {
                var salaryGet = await _odataClient.For<Models.ShiftSalary>().QueryOptions($"staffId={staff.StaffId}").FindEntryAsync();
                salary = salaryGet.Salary;
            }
            role = Constants.Role.GetStatus(staff.RoleId);
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
            {
                return RedirectToPage("/Login");
            }
            if (!Utils.isManager(HttpContext.Session.GetString("Role")))
            {
                return RedirectToPage("/Login");
            }
            var token = HttpContext.Session.GetString("Token");
            _odataClient = OdataUtils.GetODataClient(token);
            var staffTemp = await _odataClient.For<Models.Staff>().QueryOptions($"$filter=StaffId eq {id}").FindEntryAsync();
            if (staffTemp == null)
            {
                return NotFound();
            }
            if (staffTemp.Status == 0)
            {
                staffTemp.Status = 1;
            }
            else
            {
                staffTemp.Status = 0;
            }

            var myContent = JsonConvert.SerializeObject(staffTemp);
            var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
            byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
            await client.PutAsync(api + $"?id={id}", byteContent);

            return RedirectToPage("./Index");

        }
    }
}

MinistoreFE/Pages/Salesman/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Salesman
{
    public class CheckoutModel : PageModel
    {
        private ODataClient _odataClient;
        public CheckoutModel()
        {
            _odataClient = OdataUtils.GetODataClient();
        }

        public IList<Product> Product { get;set; } = default!;

        public async Task<IActionResult> OnGetAsync()
        {
            if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token"))) {
                return RedirectToPage("/Login");
            }
            if (!Utils.isSalesman(HttpContext.Session.GetString("Role"))) {
                return RedirectToPage("/Login");
            }
            _odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
            Product = new List<Product>();
            var cart = HttpContext.Session.GetCustomObjectFromSession<Cart>("Cart");
            if (cart == null) {
                cart = Utils.CreateCart(HttpContext.Session.GetString("Id"));
            }
            foreach (var item in cart.CartItems) {
                var temp = await _odataClient.For<Product>().Key(item.ProductId).Expand(p => p.Category).FindEntryAsync();
                temp.UnitsInStock = item.Quantity;
                Product.Add(temp);
            }
            return Page();
        }

        public async Task<IActionResult> OnPostSubmit() {
            if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token"))) {
                return RedirectToPage("/Login");
            }
            if (!Utils.isSalesman(HttpContext.Session.GetString("Role"))) {
                return RedirectToPage("/Login");
            }

            var cart = HttpContext.Session.GetCustomObjectFromSession<Cart>("Cart");
            if (cart == null) {
                cart = Utils.CreateCart(HttpContext.Session.GetString("Id"));
                return RedirectToPage("/Salesman/Products/Index");
            }

            _odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));

            Invoice invoice = new Invoice { StaffId = cart.StaffId, OrderDate = DateTime.Now, Status = 1, Total = 0, InvoiceDetails = new List<InvoiceDetail>() };
            foreach (var item in cart.CartItems) {
                var product = await _odataClient.For<Product>().Key(item.ProductId).Expand(p => p.Category).FindEntryAsync();
                if (product != null) {
                    var detail = new InvoiceDetail {
                        ProductId = product.ProductId,
                        Discount = item.Discount,
                        UnitPrice = product.UnitPrice,
                        Quantity = item.Quantity
                    };
                    invoice.InvoiceDetails.Add(detail);
                    invoice.Total += detail.Quantity * detail.UnitPrice * (decimal) (1 - detail.Discount);
                }
            }
            await _odataClient.For<Invoice>().Set(invoice).InsertEntryAsync();
            cart.CartItems.Clear();
            HttpContext.Session.SetObjectInSession("Cart", cart);
            return RedirectToPage("/Salesman/Products/Index");
        }

        public async Task<IActionResult> OnPostRemove(int productId) {
            if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token"))) {
                return RedirectToPage("/Login");
            }
            if (!Utils.isSalesman(HttpContext.Session.GetString("Role"))) {
                return RedirectToPage("/Login");
            }

            var cart = HttpContext.Session.GetCustomObjectFromSession<Cart>("Cart");
            if (cart == null) {
                cart = Utils.CreateCart(HttpContext.Session.GetString("Id"));
                return RedirectToPage("/Salesman/Products/Index");
            }

            var item = cart.CartItems.FirstOrDefault(p => p.ProductId == productId);
            if (item != null) {
                cart.CartItems.Remove(item);
            }
            HttpContext.Session.SetObjectInSession("Cart", cart);
            return RedirectToPage();
        }
    }
}

MinistoreFE/Pages/Salesman/Products/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Salesman.Products
{
	public class IndexModel : PageModel
	{
		private ODataClient _odataClient;
		public IndexModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		public IList<Product> Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isSalesman(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			Product = new List<Product>();
			var token = HttpContext.Session.GetString("Token");
			_odataClient = OdataUtils.GetODataClient(token);
			var temp = await _odataClient.For<Product>().Expand(p => p.Category).FindEntriesAsync();
			Product = temp.Where(p => p.UnitsInStock > 0).ToList();
			return Page();
		}

		public async Task<IActionResult> OnPostAdd(int productId)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isSalesman(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}

			var cart = HttpContext.Session.GetCustomObjectFromSession<Cart>("Cart");
			if (cart == null)
			{
				cart = Utils.CreateCart(HttpContext.Session.GetString("Id"));
			}
			var item = cart.CartItems.Find(p => p.ProductId == productId);
			if (item == null)
			{
				cart.CartItems.Add(new CartItem { ProductId = productId, Discount = 0, Quantity = 1 });
			}
			else
			{
				item.Quantity += 1;
			}
			HttpContext.Session.SetObjectInSession("Cart", cart);
			return RedirectToPage();
		}
	}
}

MinistoreFE/Pages/Salesman/Products/Details.cshtml
@page
@model MinistoreFE.Pages.Salesman.Products.DetailsModel

@{
    ViewData["Title"] = "Product Detail";
    Layout = "_LayoutSalesman";
}

<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Salesman</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item">
                    <a asp-page="/Salesman/Dashboard">Salesman</a>
                </li>
                <li class="breadcrumb-item">
                    <a asp-page="/Salesman/Products/Index">Product</a>
                </li>
                <li class="breadcrumb-item active">
                    Details
                </li>
            </ul>
        </div>
        <div class="col-auto float-end ms-auto">
            <a class="btn add-btn" asp-page="/Salesman/Products/Index">
                <i class="fa fa-list"></i> Back to List
            </a>
        </div>
        <div class="col-auto float-end ms-auto">
            <a class="btn add-btn" asp-page="/Salesman/Checkout">
                <i class="fa fa-cart-shopping"></i> Checkout
            </a>
        </div>
    </div>
</div>

@*<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Product.ProductName)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Product.ProductName)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Product.Description)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Product.Description)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Product.UnitPrice)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Product.UnitPrice)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Product.UnitsInStock)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Product.UnitsInStock)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Product.Category)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Product.Category.CategoryName)
    </dd>
</dl>*@
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title mb-0">Product Detail</h4>
            </div>
            <div class="card-body">
                <form action="#">
                    <div class="form-group-row">
                        <label class="col-form-label col-md-2">Product Name</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" readonly="true" value="@Model.Product.ProductName">
                        </div>
                    </div>
                    <div class="form-group-row">
                        <label class="col-form-label col-md-2">Description</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" readonly="true" value="@Model.Product.Description">
                        </div>
                    </div>
                    <div class="form-group-row">
                        <label class="col-form-label col-md-2">Unit Price</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" readonly="true" value="@Model.Product.UnitPrice">
                        </div>
                    </div>
                    <div class="form-group-row">
                        <label class="col-form-label col-md-2">Unit In Stock</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" readonly="true" value="@Model.Product.UnitsInStock">
                        </div>
                    </div>
                    <div class="form-group-row">
                        <label class="col-form-label col-md-2">Category</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" readonly="true" value="@Model.Product.Category.CategoryName">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MinistoreFE/Pages/Salesman/Products/Index.cshtml
@page
@model MinistoreFE.Pages.Salesman.Products.IndexModel

@{
	ViewData["Title"] = "Product list";
	Layout = "_LayoutSalesman";
}
<div class="page-header">
	<div class="row align-items-center">
		<div class="col">
			<h3 class="page-title">Salesman</h3>
			<ul class="breadcrumb">
				<li class="breadcrumb-item">
					<a asp-page="/Salesman/Dashboard">Salesman</a>
				</li>
				<li class="breadcrumb-item active">Products</li>
			</ul>
		</div>
		<div class="col-auto float-end ms-auto">
			<a class="btn add-btn" asp-page="/Salesman/Checkout">
				<i class="fa fa-cart-shopping"></i> Checkout
			</a>
		</div>
	</div>
</div>

<div class="row filter-row">
	<div class="col-sm-6 col-md-9">
		<div class="form-group form-focus">
			<input type="text" class="form-control floating">
			<label class="focus-label">Product Name</label>
		</div>
	</div>
	<div class="col-sm-6 col-md-3">
		<div class="d-grid">
			<a href="#" class="btn btn-success w-100"> Search </a>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-12">
		<div class="table-responsive">
			<table class="table table-striped custom-table datatable">
				<thead>
					<tr>
						<th>
							@Html.DisplayNameFor(model => model.Product[0].ProductName)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.Product[0].Description)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.Product[0].UnitPrice)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.Product[0].UnitsInStock)
						</th>
						<th>
							@Html.DisplayNameFor(model => model.Product[0].Category)
						</th>
						<th>
							Action
						</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model.Product)
					{
						<tr>
							<td>
								@Html.DisplayFor(modelItem => item.ProductName)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Description)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.UnitPrice)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.UnitsInStock)
							</td>
							<td>
								@Html.DisplayFor(modelItem => item.Category.CategoryName)
							</td>
							<td>

								<div class="d-flex justify-content-between gap-2">
									<a asp-page="./Details" asp-route-id="@item.ProductId">
										Details
									</a>
									<form asp-page-handler="Add" method="post">
										<input type="hidden" name="productId" asp-for="@item.ProductId" />
										<input type="submit" class="dropdown-item" value="Add to Cart">
									</form>
								</div>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
</div>