MinistoreFE/Models/Duty.cs
using System;
using System.Collections.Generic;

namespace MinistoreFE.Models
{
    public partial class Duty
    {
        public int DutyId { get; set; }
        public int ShiftId { get; set; }
        public int RoleId { get; set; }
        public string AssignedTo { get; set; } = null!;
        public byte? Status { get; set; }

        public virtual Staff AssignedToNavigation { get; set; } = null!;
        public virtual WorkShift Shift { get; set; } = null!;
    }
}

MinistoreFE/Pages/Manager/Duty.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Constants;
using MinistoreFE.Models;
using MinistoreFE.Request;
using Newtonsoft.Json;
using Simple.OData.Client;
using System.Globalization;
using System.Net.Http.Headers;

namespace MinistoreFE.Pages.Manager
{
	public class DutyModel : PageModel
	{
		private ODataClient _odataClient;
		private HttpClient client;
		private string WorkShiftApi = "https://localhost:7036/odata/WorkShifts";
		private string DutyApi = "https://localhost:7036/odata/Duties";
		private string ManagerId;
		public DutyModel()
		{
			_odataClient = OdataUtils.GetODataClient();
			client = new HttpClient();
			var contentType = new MediaTypeWithQualityHeaderValue("application/json");
			client.DefaultRequestHeaders.Accept.Add(contentType);
			Date = DateTime.Now;
		}

		public List<DateOnly> Dates { get; set; }
		public List<WorkShift> WorkShifts { get; set; }
		public List<Models.Staff> AllStaffs { get; set; }
		public List<Models.Staff> FreeStaffs { get; set; } = new List<Models.Staff>();
		public WorkShift CurrentShift { get; set; }
		public DateTime Date { get; set; }
		public async Task<IActionResult> OnGetAsync()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			ManagerId = HttpContext.Session.GetString("Id");
			var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
			WorkShifts = temp.ToList();
			var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
			AllStaffs = staffTmp.Where(s => s.Status == (byte)Status.Available && !Role.IsManager(s.RoleId)).ToList();
			if (WorkShifts.Count == 0)
			{
				WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
				var myContent = JsonConvert.SerializeObject(request);
				var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
				byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
				await client.PostAsync(WorkShiftApi, byteContent);
				temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
				WorkShifts = temp.ToList();
			}
			return Page();
		}
		public async Task<IActionResult> OnPost(string date)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			ManagerId = HttpContext.Session.GetString("Id");

			Date = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
			var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
			WorkShifts = temp.ToList();
			var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
			AllStaffs = staffTmp.Where(s => s.Status == (byte)Status.Available && !Role.IsManager(s.RoleId)).ToList();
			if (WorkShifts.Count == 0)
			{
				WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
				var myContent = JsonConvert.SerializeObject(request);
				var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
				byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
				client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
				await client.PostAsync(WorkShiftApi, byteContent);
				temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
				WorkShifts = temp.ToList();
			}
			return Page();
		}
		public async Task<IActionResult> OnPostUpdate(DateTime date, int dutyId, byte status)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			ManagerId = HttpContext.Session.GetString("Id");

			Models.Duty duty = new Models.Duty { DutyId = dutyId, Status = status };
			var myContent = JsonConvert.SerializeObject(duty);
			var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
			byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
			await client.PostAsync($"{DutyApi}/Update", byteContent);
			return await OnPost(date.ToString("dd/MM/yyyy"));
		}
		public async Task<IActionResult> OnPostDelete(DateTime date, int dutyId)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			ManagerId = HttpContext.Session.GetString("Id");
			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
			await client.DeleteAsync($"{DutyApi}/{dutyId}");
			return await OnPost(date.ToString("dd/MM/yyyy"));
		}
		public async Task<IActionResult> OnPostCreate(DateTime date, int shiftId, string[] staffId)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			ManagerId = HttpContext.Session.GetString("Id");

			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));

			Models.Duty duty;
			foreach (string id in staffId)
			{
				duty = new Models.Duty { ShiftId = shiftId, AssignedTo = id };
				var myContent = JsonConvert.SerializeObject(duty);
				var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
				byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
				await client.PostAsync(DutyApi, byteContent);
			}
			return await OnPost(date.ToString("dd/MM/yyyy"));
		}
	}
}

MinistoreFE/Pages/Manager/Duty/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Models;
using MinistoreFE.Request;
using Newtonsoft.Json;
using Simple.OData.Client;
using System.Globalization;
using System.Net.Http.Headers;

namespace MinistoreFE.Pages.Manager.Duty
{
    public class IndexModel : PageModel
    {
        private ODataClient _odataClient;
        private HttpClient client;
        private string WorkShiftApi = "https://localhost:7036/odata/WorkShifts";
        private string ManagerId = "VyLT1";
        public IndexModel()
        {
            _odataClient = OdataUtils.GetODataClient();
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            Date = DateTime.Now;
        }

        public List<DateOnly> Dates { get; set; }
        public List<WorkShift> WorkShifts { get; set; }
        public List<string> StaffIds { get; set; }
        public List<string> FreeStaffIds { get; set; }
        public DateTime Date { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
            WorkShifts = temp.ToList();
            var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
            StaffIds = staffTmp.Select(s => s.StaffId).ToList();
            if (WorkShifts.Count == 0)
            {
                WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
                var myContent = JsonConvert.SerializeObject(request);
                var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                await client.PostAsync(WorkShiftApi, byteContent);
                temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
                WorkShifts = temp.ToList();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(string date)
        {
            Date = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
            WorkShifts = temp.ToList();
            var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
            StaffIds = staffTmp.Select(s => s.StaffId).ToList();
            if (WorkShifts.Count == 0)
            {
                WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
                var myContent = JsonConvert.SerializeObject(request);
                var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                await client.PostAsync(WorkShiftApi, byteContent);
                temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
                WorkShifts = temp.ToList();
            }
            return Page();
        }
    }
}

MinistoreFE/Pages/Manager/Products/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class CreateModel : PageModel
	{
		private ODataClient _odataClient;

		public CreateModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		[BindProperty]
		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			var temp = await _odataClient.For<Category>().FindEntriesAsync();
			ViewData["Category"] = new SelectList(temp.ToList(), "CategoryId", "CategoryName");
			return Page();
		}

		public async Task<IActionResult> OnPostCreate()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));

			Product.Status = 1;
			Product.ProductStatus = 1;
			var temp = await _odataClient.For<Product>().Set(Product).InsertEntryAsync();
			return RedirectToPage("./Index");
		}
	}
}

MinistoreFE/Pages/Manager/Products/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class DeleteModel : PageModel
	{
		private ODataClient _odataClient;

		public DeleteModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product = await _odataClient.For<Product>().Key(id).Expand(p => p.Category).FindEntryAsync();
			return Page();
		}

		public async Task<IActionResult> OnPostDelete(int? productId)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			await _odataClient.For<Product>().Key(productId).DeleteEntryAsync();
			return RedirectToPage("./Index");
		}
	}
}

MinistoreFE/Pages/Manager/Products/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class DetailsModel : PageModel
	{
		private ODataClient _odataClient;

		public DetailsModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product = await _odataClient.For<Product>().Key(id).Expand(p => p.Category).FindEntryAsync();
			return Page();
		}
	}
}

MinistoreFE/Pages/Manager/Products/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class EditModel : PageModel
	{
		private ODataClient _odataClient;

		public EditModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		[BindProperty]
		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product = await _odataClient.For<Product>().Key(id).Expand(p => p.Category).FindEntryAsync();
			var temp = await _odataClient.For<Category>().FindEntriesAsync();
			ViewData["Category"] = new SelectList(temp.ToList(), "CategoryId", "CategoryName");
			return Page();
		}

		public async Task<IActionResult> OnPostEdit()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product.Status = 1;
			Product.ProductStatus = 1;
			await _odataClient.For<Product>().Key(Product.ProductId).Set(Product).UpdateEntryAsync();
			return RedirectToPage("./Details", new { id = Product.ProductId.ToString() });
		}
	}
}

MinistoreFE/Pages/Manager/Duty.cshtml
@page
@model MinistoreFE.Pages.Manager.DutyModel
@using MinistoreFE.Constants;
@using MinistoreFE.Models;

@{
	ViewData["Title"] = "Duty";
	Layout = "_LayoutManager";
}
@section scripts{
	<script>
		if (location.href.includes('?')) {
			history.pushState({}, null, location.href.split('?')[0]);
		}
	</script>
}
<div class="page-header">
	<div class="row align-items-center">
		<div class="col">
			<h3 class="page-title">Manager</h3>
			<ul class="breadcrumb">
				<li class="breadcrumb-item">
					<a asp-page="/Manager/Staff/Index">Manager</a>
				</li>
				<li class="breadcrumb-item active">Duty</li>
			</ul>
		</div>
	</div>
</div>

<form class="row filter-row" method="post">
	<div class="col-sm-6 col-md-3 col-lg-3 col-xl-2 col-12">
		<div class="form-group form-focus">
			<div class="cal-icon">
				<input class="form-control floating datetimepicker" name="date" value="@Model.Date.ToString("dd/MM/yyyy")" type="text">
			</div>
			<label class="focus-label">Date</label>
		</div>
	</div>
	<div class="col-sm-6 col-md-3 col-lg-3 col-xl-2 col-12">
		<input type="submit" href="#" class="btn btn-success w-100" value="Search" />
	</div>
</form>
<div>
	<div class="table-responsive">
		<table class="table custom-table">
			<thead>
				<tr>
					@foreach (var item in Model.WorkShifts)
					{
						<th>@item.StartTime.ToString("HH:mm") - @item.EndTime.ToString("HH:mm")</th>
					}
				</tr>
			</thead>
			<tbody>
				<tr>
					@foreach (var item in Model.WorkShifts)
					{
						<td class="p-0 bg-soft-dark">
							<div class="py-3 d-flex justify-content-center">
								<a href="#" class="btn w-48" data-bs-toggle="modal" data-bs-target="#add-@item.ShiftId"><i class="fa fa-plus"></i> Add </a>
							</div>
							@foreach (var duty in item.Duties)
							{
								<div class="card profile-box flex-fill">
									<div class="card-body">
										<div class="dropdown dropdown-action d-flex justify-content-end">
											<a href="#" style="height:24px;" class="action-icon dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
												<i class="fa fa-ellipsis"></i>
											</a>
											<div class="dropdown-menu dropdown-menu-right" style="">
												<a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#edit-@duty.DutyId">
													<i class="fa fa-pencil m-r-5"></i>
													Edit
												</a>
												<a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#delete-@duty.DutyId">
													<i class="fa fa-trash-can m-r-5"></i>
													Delete
												</a>
											</div>
										</div>
										<ul class="personal-info">
											<li>
												<div class="title">Staff</div>
												<div class="text">@duty.AssignedTo</div>
											</li>
											<li>
												<div class="title">Status</div>
												<div class="text">
													<span class="badge bg-inverse-@DutyStatus.GetClassString(duty.Status)">@DutyStatus.GetStatus(duty.Status)</span>
												</div>
											</li>
										</ul>
									</div>
								</div>
							}
						</td>
					}
				</tr>
			</tbody>
		</table>
	</div>
	@foreach(var item in Model.WorkShifts)
	{
		<div>
			<div id="add-@item.ShiftId" class="modal custom-modal fade" style="display: none;" aria-hidden="true">
				<div class="modal-dialog modal-md" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title">Add Duty</h5>
							<button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">×</span>
							</button>
						</div>
						<div class="modal-body">
							<form method="post" asp-page-handler="Create">
								<input hidden type="number" value="@item.ShiftId" name="shiftId" />
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											@{
												Model.FreeStaffs =
												// Get all available staff
													Model.AllStaffs
													// Get the staff not in current shift duty
													.Where(staff => !item.Duties
													.Select(d => d.AssignedTo)
													.Any(dutyStaff => dutyStaff.Equals(staff.StaffId)))
													.ToList();
											}
											@if (!Model.FreeStaffs.Any())
											{
												<div>There is no available staff for this shift.</div>
											} else
											{
												<table class="table table-striped mb-0">
													<thead>
														<tr>
															<th></th>
															<th>ID</th>
															<th>Name</th>
															<th>Role</th>
														</tr>
													</thead>
													<tbody>
														@foreach (Models.Staff staff in Model.FreeStaffs)
														{
															<tr>
																<td>
																	<input class="me-2 default_expense_approval" name="staffId" value="@staff.StaffId" type="checkbox">
																</td>
																<td>@staff.StaffId</td>
																<td>@staff.StaffName</td>
																<td>@staff.RoleId</td>
															</tr>
														}
													</tbody>
												</table>
											}
										</div>
									</div>
								</div>
								<input hidden name="date" value="@Model.Date" type="datetime" />
								
								@if (Model.FreeStaffs.Any())
								{
									<div class="submit-section">
										<button class="btn btn-primary submit-btn">Add</button>
									</div>
								}
							</form>
						</div>
					</div>
				</div>
			</div>
			@foreach(var duty in item.Duties)
			{
				<div id="delete-@duty.DutyId" class="modal custom-modal fade" style="display: none;" aria-hidden="true">
					<div class="modal-dialog modal-md" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title">Delete Duty</h5>
								<button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">×</span>
								</button>
							</div>
							<div class="modal-body">
								<form method="post" asp-page-handler="Delete">
									<div>Are you sure to delete this duty of @duty.AssignedTo?</div>
									<input hidden name="date" value="@Model.Date" type="datetime" />
									<input hidden name="dutyId" value="@duty.DutyId" type="number" />
									<div class="submit-section">
										<button class="btn btn-primary submit-btn">Delete</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
				<div id="edit-@duty.DutyId" class="modal custom-modal fade" style="display: none;" aria-hidden="true">
					<div class="modal-dialog modal-md" role="document">
						<div class="modal-content">
							<div class="modal-header">
								<h5 class="modal-title">Edit Duty</h5>
								<button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">×</span>
								</button>
							</div>
							<div class="modal-body">
								<form method="post" asp-page-handler="Update">
									<div class="row">
										<div class="col-md-12">
											<div class="form-group">
												<label>Staff</label>
												<input hidden class="form-control" name="dutyId" value="@duty.DutyId" type="text">
												<input readonly class="form-control" value="@duty.AssignedTo" type="text">
												<input hidden name="date" value="@Model.Date" type="datetime" />
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-md-12">
											<div class="form-group">
												<label>Status</label>
												<div class="d-flex justify-content-between">
													@for (byte j = 0; j < 3; j++)
													{
														<label class="radio-inline d-flex justify-content-start align-items-center">
															<input id="radio-single1" class="me-2 default_expense_approval" checked="@(j == duty.Status)" value="@j" name="status" type="radio">
															<span class="badge bg-inverse-@DutyStatus.GetClassString(j)">@DutyStatus.GetStatus(j)</span>
														</label>
													}
												</div>
											</div>
										</div>
									</div>
									<div class="submit-section">
										<button class="btn btn-primary submit-btn">Edit</button>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			}
		</div>
	}
</div>
<style>
	.card {
		margin-bottom: 0;
		border-radius: 0;
	}

	th {
		width: 250px;
		text-align: center;
	}

	.table {
		width: fit-content;
	}

		.table td {
			vertical-align: top;
			padding: 0;
		}

	.dropdown-menu {
		min-width: 7rem;
	}

	.text {
		margin-right: 5px;
	}

	.title {
		margin-right: 20px;
	}

	.submit-section {
		margin-top: 30px;
	}
</style>