MinistoreFE/Models/Product.cs
using System;
using System.Collections.Generic;

namespace MinistoreFE.Models
{
    public partial class Product
    {
        public Product()
        {
            InvoiceDetails = new HashSet<InvoiceDetail>();
        }

        public int ProductId { get; set; }
        public string CategoryId { get; set; } = null!;
        public string ProductName { get; set; } = null!;
        public string Description { get; set; } = null!;
        public decimal UnitPrice { get; set; }
        public int UnitsInStock { get; set; }
        public byte? ProductStatus { get; set; }
        public byte? Status { get; set; }

        public virtual Category Category { get; set; } = null!;
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}

MinistoreFE/Pages/Manager/Duty.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Constants;
using MinistoreFE.Models;
using MinistoreFE.Request;
using Newtonsoft.Json;
using Simple.OData.Client;
using System.Globalization;
using System.Net.Http.Headers;

namespace MinistoreFE.Pages.Manager
{
	public class DutyModel : PageModel
	{
		private ODataClient _odataClient;
		private HttpClient client;
		private string WorkShiftApi = "https://localhost:7036/odata/WorkShifts";
		private string DutyApi = "https://localhost:7036/odata/Duties";
		private string ManagerId;
		public DutyModel()
		{
			_odataClient = OdataUtils.GetODataClient();
			client = new HttpClient();
			var contentType = new MediaTypeWithQualityHeaderValue("application/json");
			client.DefaultRequestHeaders.Accept.Add(contentType);
			Date = DateTime.Now;
		}

		public List<DateOnly> Dates { get; set; }
		public List<WorkShift> WorkShifts { get; set; }
		public List<Models.Staff> AllStaffs { get; set; }
		public List<Models.Staff> FreeStaffs { get; set; } = new List<Models.Staff>();
		public WorkShift CurrentShift { get; set; }
		public DateTime Date { get; set; }
		public async Task<IActionResult> OnGetAsync()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			ManagerId = HttpContext.Session.GetString("Id");
			var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
			WorkShifts = temp.ToList();
			var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
			AllStaffs = staffTmp.Where(s => s.Status == (byte)Status.Available && !Role.IsManager(s.RoleId)).ToList();
			if (WorkShifts.Count == 0)
			{
				WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
				var myContent = JsonConvert.SerializeObject(request);
				var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
				byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
				await client.PostAsync(WorkShiftApi, byteContent);
				temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
				WorkShifts = temp.ToList();
			}
			return Page();
		}
		public async Task<IActionResult> OnPost(string date)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			ManagerId = HttpContext.Session.GetString("Id");

			Date = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
			var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
			WorkShifts = temp.ToList();
			var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
			AllStaffs = staffTmp.Where(s => s.Status == (byte)Status.Available && !Role.IsManager(s.RoleId)).ToList();
			if (WorkShifts.Count == 0)
			{
				WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
				var myContent = JsonConvert.SerializeObject(request);
				var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
				byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
				client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
				await client.PostAsync(WorkShiftApi, byteContent);
				temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
				WorkShifts = temp.ToList();
			}
			return Page();
		}
		public async Task<IActionResult> OnPostUpdate(DateTime date, int dutyId, byte status)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			ManagerId = HttpContext.Session.GetString("Id");

			Models.Duty duty = new Models.Duty { DutyId = dutyId, Status = status };
			var myContent = JsonConvert.SerializeObject(duty);
			var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
			byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
			await client.PostAsync($"{DutyApi}/Update", byteContent);
			return await OnPost(date.ToString("dd/MM/yyyy"));
		}
		public async Task<IActionResult> OnPostDelete(DateTime date, int dutyId)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			ManagerId = HttpContext.Session.GetString("Id");
			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));
			await client.DeleteAsync($"{DutyApi}/{dutyId}");
			return await OnPost(date.ToString("dd/MM/yyyy"));
		}
		public async Task<IActionResult> OnPostCreate(DateTime date, int shiftId, string[] staffId)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			ManagerId = HttpContext.Session.GetString("Id");

			client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Session.GetString("Token"));

			Models.Duty duty;
			foreach (string id in staffId)
			{
				duty = new Models.Duty { ShiftId = shiftId, AssignedTo = id };
				var myContent = JsonConvert.SerializeObject(duty);
				var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
				byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
				await client.PostAsync(DutyApi, byteContent);
			}
			return await OnPost(date.ToString("dd/MM/yyyy"));
		}
	}
}

MinistoreFE/Pages/Manager/Duty/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Models;
using MinistoreFE.Request;
using Newtonsoft.Json;
using Simple.OData.Client;
using System.Globalization;
using System.Net.Http.Headers;

namespace MinistoreFE.Pages.Manager.Duty
{
    public class IndexModel : PageModel
    {
        private ODataClient _odataClient;
        private HttpClient client;
        private string WorkShiftApi = "https://localhost:7036/odata/WorkShifts";
        private string ManagerId = "VyLT1";
        public IndexModel()
        {
            _odataClient = OdataUtils.GetODataClient();
            client = new HttpClient();
            var contentType = new MediaTypeWithQualityHeaderValue("application/json");
            client.DefaultRequestHeaders.Accept.Add(contentType);
            Date = DateTime.Now;
        }

        public List<DateOnly> Dates { get; set; }
        public List<WorkShift> WorkShifts { get; set; }
        public List<string> StaffIds { get; set; }
        public List<string> FreeStaffIds { get; set; }
        public DateTime Date { get; set; }
        public async Task<IActionResult> OnGetAsync()
        {
            var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
            WorkShifts = temp.ToList();
            var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
            StaffIds = staffTmp.Select(s => s.StaffId).ToList();
            if (WorkShifts.Count == 0)
            {
                WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
                var myContent = JsonConvert.SerializeObject(request);
                var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                await client.PostAsync(WorkShiftApi, byteContent);
                temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
                WorkShifts = temp.ToList();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(string date)
        {
            Date = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            var temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
            WorkShifts = temp.ToList();
            var staffTmp = await _odataClient.For<Models.Staff>().FindEntriesAsync();
            StaffIds = staffTmp.Select(s => s.StaffId).ToList();
            if (WorkShifts.Count == 0)
            {
                WorkShiftRequest request = new WorkShiftRequest(Date, ManagerId, 0);
                var myContent = JsonConvert.SerializeObject(request);
                var byteContent = new ByteArrayContent(System.Text.Encoding.UTF8.GetBytes(myContent));
                byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
                await client.PostAsync(WorkShiftApi, byteContent);
                temp = await _odataClient.For<WorkShift>().QueryOptions($"year={Date.Year}&month={Date.Month}&date={Date.Day}").Expand(d => d.Duties).FindEntriesAsync();
                WorkShifts = temp.ToList();
            }
            return Page();
        }
    }
}

MinistoreFE/Pages/Manager/Products/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class CreateModel : PageModel
	{
		private ODataClient _odataClient;

		public CreateModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		[BindProperty]
		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			var temp = await _odataClient.For<Category>().FindEntriesAsync();
			ViewData["Category"] = new SelectList(temp.ToList(), "CategoryId", "CategoryName");
			return Page();
		}

		public async Task<IActionResult> OnPostCreate()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));

			Product.Status = 1;
			Product.ProductStatus = 1;
			var temp = await _odataClient.For<Product>().Set(Product).InsertEntryAsync();
			return RedirectToPage("./Index");
		}
	}
}

MinistoreFE/Pages/Manager/Products/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class DeleteModel : PageModel
	{
		private ODataClient _odataClient;

		public DeleteModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product = await _odataClient.For<Product>().Key(id).Expand(p => p.Category).FindEntryAsync();
			return Page();
		}

		public async Task<IActionResult> OnPostDelete(int? productId)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			await _odataClient.For<Product>().Key(productId).DeleteEntryAsync();
			return RedirectToPage("./Index");
		}
	}
}

MinistoreFE/Pages/Manager/Products/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class DetailsModel : PageModel
	{
		private ODataClient _odataClient;

		public DetailsModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product = await _odataClient.For<Product>().Key(id).Expand(p => p.Category).FindEntryAsync();
			return Page();
		}
	}
}

MinistoreFE/Pages/Manager/Products/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MinistoreFE.Models;
using Simple.OData.Client;

namespace MinistoreFE.Pages.Manager.Products
{
	public class EditModel : PageModel
	{
		private ODataClient _odataClient;

		public EditModel()
		{
			_odataClient = OdataUtils.GetODataClient();
		}

		[BindProperty]
		public Product Product { get; set; } = default!;

		public async Task<IActionResult> OnGetAsync(int? id)
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product = await _odataClient.For<Product>().Key(id).Expand(p => p.Category).FindEntryAsync();
			var temp = await _odataClient.For<Category>().FindEntriesAsync();
			ViewData["Category"] = new SelectList(temp.ToList(), "CategoryId", "CategoryName");
			return Page();
		}

		public async Task<IActionResult> OnPostEdit()
		{
			if (!Utils.isLogin(HttpContext.Session.GetString("Id"), HttpContext.Session.GetString("Role"), HttpContext.Session.GetString("Token")))
			{
				return RedirectToPage("/Login");
			}
			if (!Utils.isManager(HttpContext.Session.GetString("Role")))
			{
				return RedirectToPage("/Login");
			}
			_odataClient = OdataUtils.GetODataClient(HttpContext.Session.GetString("Token"));
			Product.Status = 1;
			Product.ProductStatus = 1;
			await _odataClient.For<Product>().Key(Product.ProductId).Set(Product).UpdateEntryAsync();
			return RedirectToPage("./Details", new { id = Product.ProductId.ToString() });
		}
	}
}

MinistoreFE/Pages/Manager/Products/Create.cshtml
@page
@model MinistoreFE.Pages.Manager.Products.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "_LayoutManager";
}

<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Manager</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item">
                    <a asp-page="/Manager/Staff/Index">Manager</a>
                </li>
                <li class="breadcrumb-item">
                    <a asp-page="./Index">Product</a>
                </li>
                <li class="breadcrumb-item active">Edit</li>
            </ul>
        </div>
        <div class="col-auto float-end ms-auto">
            <a class="btn btn-secondary" asp-page="./Index">
                <i class="fa fa-list"></i> Back to List
            </a>
        </div>
        @*<div class="col-auto float-end ms-auto">
            <a class="btn btn-primary" asp-page="/Manager/Create">
                <i class="fa fa-plus"></i> Add Product
            </a>
        </div>*@
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="col card-title mb-0">Product Detail</h4>
                @*<div class="dropdown dropdown-action float-end">
                    <a href="#" class="action-icon dropdown-toggle"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="material-icons">more_vert</i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" asp-page="./Details" asp-route-id="@Model.Product.ProductId">
                            Details
                        </a>
                        <a class="dropdown-item" asp-page="./Delete" asp-route-id="@Model.Product.ProductId">
                            Delete
                        </a>
                    </div>
                </div>*@
            </div>
            <div class="card-body">
                <form method="post" asp-page-handler="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group row">
                        <label asp-for="Product.ProductName" class="col-form-label col-md-2"></label>
                        <div class="col-md-10">
                            <input asp-for="Product.ProductName" class="form-control" />
                        </div>
                        <span asp-validation-for="Product.ProductName" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Product.Description" class="col-form-label col-md-2"></label>
                        <div class="col-md-10">
                            <input asp-for="Product.Description" class="form-control" />
                        </div>
                        <span asp-validation-for="Product.Description" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Product.UnitPrice" class="col-form-label col-md-2"></label>
                        <div class="col-md-10">
                            <input asp-for="Product.UnitPrice" class="form-control" />
                        </div>
                        <span asp-validation-for="Product.UnitPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Product.UnitsInStock" class="col-form-label col-md-2"></label>
                        <div class="col-md-10">
                            <input asp-for="Product.UnitsInStock" class="form-control" />
                        </div>
                        <span asp-validation-for="Product.UnitsInStock" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Product.CategoryId" class="col-form-label col-md-2"></label>
                        <div class="col-md-10">
                            <select asp-for="Product.CategoryId" class="form-control col-md-10" asp-items="ViewBag.Category"></select>
                        </div>
                        <span asp-validation-for="Product.CategoryId" class="text-danger"></span>
                    </div>
                    <div class="form-group-row">
                        <input type="submit" class="btn btn-success" value="Create" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MinistoreFE/Pages/Manager/Products/Edit.cshtml
@page
@model MinistoreFE.Pages.Manager.Products.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "_LayoutManager";
}

<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Manager</h3>
            <ul class="breadcrumb">
                <li class="breadcrumb-item">
                    <a asp-page="/Manager/Staff/Index">Manager</a>
                </li>
                <li class="breadcrumb-item">
                    <a asp-page="/Manager/Products/Index">Product</a>
                </li>
                <li class="breadcrumb-item active">Edit</li>
            </ul>
        </div>
        <div class="col-auto float-end ms-auto">
            <a class="btn btn-secondary" asp-page="./Index">
                <i class="fa fa-list"></i> Back to List
            </a>
        </div>
        <div class="col-auto float-end ms-auto">
            <a class="btn btn-primary" asp-page="./Create">
                <i class="fa fa-plus"></i> Add Product
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="col card-title mb-0">Product Detail</h4>
                <div class="dropdown dropdown-action float-end">
                    <a href="#" class="action-icon dropdown-toggle"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="material-icons">more_vert</i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" asp-page="./Details" asp-route-id="@Model.Product.ProductId">
                            Details
                        </a>
                        <a class="dropdown-item" asp-page="./Delete" asp-route-id="@Model.Product.ProductId">
                            Delete
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form method="post" asp-page-handler="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Product.ProductId" />
                    <div class="form-group row">
                        <label asp-for="Product.ProductName" class="col-form-label col-md-2"></label>
                        <div class="col-md-10">
                            <input asp-for="Product.ProductName" class="form-control" />
                        </div>
                        <span asp-validation-for="Product.ProductName" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Product.Description" class="col-form-label col-md-2"></label>
                        <div class="col-md-10">
                            <input asp-for="Product.Description" class="form-control" />
                        </div>
                        <span asp-validation-for="Product.Description" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Product.UnitPrice" class="col-form-label col-md-2"></label>
                        <div class="col-md-10">
                            <input asp-for="Product.UnitPrice" class="form-control" />
                        </div>
                        <span asp-validation-for="Product.UnitPrice" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Product.UnitsInStock" class="col-form-label col-md-2"></label>
                        <div class="col-md-10">
                            <input asp-for="Product.UnitsInStock" class="form-control" />
                        </div>
                        <span asp-validation-for="Product.UnitsInStock" class="text-danger"></span>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Product.CategoryId" class="col-form-label col-md-2"></label>
                        <div class="col-md-10">
                            <select asp-for="Product.CategoryId" class="form-control col-md-10" asp-items="ViewBag.Category"></select>
                        </div>
                        <span asp-validation-for="Product.CategoryId" class="text-danger"></span>
                    </div>
                    <div class="form-group-row">
                        <input type="submit" class="btn btn-success" value="Save"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}